var searchData=
[
  ['sensor_1945',['Sensor',['../classsf_1_1Sensor.html',1,'sf']]],
  ['sensorevent_1946',['SensorEvent',['../structsf_1_1Event_1_1SensorEvent.html',1,'sf::Event']]],
  ['shader_1947',['Shader',['../classsf_1_1Shader.html',1,'sf']]],
  ['shape_1948',['Shape',['../classsf_1_1Shape.html',1,'sf']]],
  ['sizeevent_1949',['SizeEvent',['../structsf_1_1Event_1_1SizeEvent.html',1,'sf::Event']]],
  ['socket_1950',['Socket',['../classsf_1_1Socket.html',1,'sf']]],
  ['socketselector_1951',['SocketSelector',['../classsf_1_1SocketSelector.html',1,'sf']]],
  ['sound_1952',['Sound',['../classsf_1_1Sound.html',1,'sf']]],
  ['soundbuffer_1953',['SoundBuffer',['../classsf_1_1SoundBuffer.html',1,'sf']]],
  ['soundbufferrecorder_1954',['SoundBufferRecorder',['../classsf_1_1SoundBufferRecorder.html',1,'sf']]],
  ['soundfilefactory_1955',['SoundFileFactory',['../classsf_1_1SoundFileFactory.html',1,'sf']]],
  ['soundfilereader_1956',['SoundFileReader',['../classsf_1_1SoundFileReader.html',1,'sf']]],
  ['soundfilewriter_1957',['SoundFileWriter',['../classsf_1_1SoundFileWriter.html',1,'sf']]],
  ['soundrecorder_1958',['SoundRecorder',['../classsf_1_1SoundRecorder.html',1,'sf']]],
  ['soundsource_1959',['SoundSource',['../classsf_1_1SoundSource.html',1,'sf']]],
  ['soundstream_1960',['SoundStream',['../classsf_1_1SoundStream.html',1,'sf']]],
  ['span_1961',['Span',['../structsf_1_1Music_1_1Span.html',1,'sf::Music']]],
  ['span_3c_20uint64_20_3e_1962',['Span&lt; Uint64 &gt;',['../structsf_1_1Music_1_1Span.html',1,'sf::Music']]],
  ['sprite_1963',['Sprite',['../classsf_1_1Sprite.html',1,'sf']]],
  ['string_1964',['String',['../classdoctest_1_1String.html',1,'doctest::String'],['../classsf_1_1String.html',1,'sf::String']]],
  ['stringcontains_1965',['StringContains',['../classdoctest_1_1AssertData_1_1StringContains.html',1,'doctest::AssertData']]],
  ['stringmaker_1966',['StringMaker',['../structdoctest_1_1StringMaker.html',1,'doctest']]],
  ['stringmakerbase_1967',['StringMakerBase',['../structdoctest_1_1detail_1_1StringMakerBase.html',1,'doctest::detail']]],
  ['stringmakerbase_3c_20detail_3a_3ahas_5finsertion_5foperator_3c_20t_20_3e_3a_3avalue_7c_7cdetail_3a_3atypes_3a_3ais_5fpointer_3c_20t_20_3e_3a_3avalue_7c_7cdetail_3a_3atypes_3a_3ais_5farray_3c_20t_20_3e_3a_3avalue_20_3e_1968',['StringMakerBase&lt; detail::has_insertion_operator&lt; T &gt;::value||detail::types::is_pointer&lt; T &gt;::value||detail::types::is_array&lt; T &gt;::value &gt;',['../structdoctest_1_1detail_1_1StringMakerBase.html',1,'doctest::detail']]],
  ['stringmakerbase_3c_20true_20_3e_1969',['StringMakerBase&lt; true &gt;',['../structdoctest_1_1detail_1_1StringMakerBase_3_01true_01_4.html',1,'doctest::detail']]],
  ['subcase_1970',['Subcase',['../structdoctest_1_1detail_1_1Subcase.html',1,'doctest::detail']]],
  ['subcasesignature_1971',['SubcaseSignature',['../structdoctest_1_1SubcaseSignature.html',1,'doctest']]]
];
